### PR TITLE
feat: add support for new *_symbols methods in SII

### PR DESCRIPTION
**Pull request by AayushSabharwal**
Requires https://github.com/SciML/SymbolicIndexingInterface.jl/pull/18

## Checklist

- [x] Appropriate tests were added
- [x] Any code changes were done in a way that does not break public API
- [x] All documentation related to code changes were updated
- [x] The new code follows the
  [contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
  [COLPRAC](https://github.com/SciML/COLPRAC).
- [x] Any new documentation only uses public API

### CODE REVIEW

**Comment by AayushSabharwal** [comment]
Wait what, how are there 11 ambiguities now

**Comment by ChrisRackauckas** [comment]
v1.10 released.

**Comment by AayushSabharwal** [comment]
```julia
julia> using RecursiveArrayTools, Aqua

julia> Aqua.detect_ambiguities(RecursiveArrayTools)
1-element Vector{Tuple{Method, Method}}:
 (ldiv!(A::T, b::ArrayPartition) where T<:Hessenberg @ RecursiveArrayTools ~/Julia/SciML/RecursiveArrayTools.jl/src/array_partition.jl:431, ldiv!(F::LinearAlgebra.Hessenberg{<:Complex, <:Any, <:AbstractMatrix{<:Real}}, B::AbstractVecOrMat{<:Complex}) @ LinearAlgebra ~/.julia/juliaup/julia-1.9.4+0.aarch64.apple.darwin14/share/julia/stdlib/v1.9/LinearAlgebra/src/hessenberg.jl:668)

julia> Aqua.detect_ambiguities(RecursiveArrayTools; recursive=true)
1-element Vector{Tuple{Method, Method}}:
 (ldiv!(A::T, b::ArrayPartition) where T<:Hessenberg @ RecursiveArrayTools ~/Julia/SciML/RecursiveArrayTools.jl/src/array_partition.jl:431, ldiv!(F::LinearAlgebra.Hessenberg{<:Complex, <:Any, <:AbstractMatrix{<:Real}}, B::AbstractVecOrMat{<:Complex}) @ LinearAlgebra ~/.julia/juliaup/julia-1.9.4+0.aarch64.apple.darwin14/share/julia/stdlib/v1.9/LinearAlgebra/src/hessenberg.jl:668)
```

Somehow I only get 1

**Comment by AayushSabharwal** [comment]
Ah, I see

**Comment by ChrisRackauckas** [comment]
Downstream is expected failure until downstream is handled.

**Pull request merged**
