### PR TITLE
fix recursivecopy

### PR DESCRIPTION
**Pull request by ranocha**
As discussed in https://github.com/SciML/OrdinaryDiffEq.jl/issues/1386 and suggested by @ChrisRackauckas.

Closes https://github.com/SciML/OrdinaryDiffEq.jl/issues/1386

### CODE REVIEW

**Comment by jlchan** [comment]
Should I add `ArrayInterface.ismutable(x::StructArray) = true` before marking https://github.com/SciML/OrdinaryDiffEq.jl/issues/1386 as closed?

**Comment by ranocha** [comment]
No, you don't need that - it's the default

**Comment by ranocha** [comment]
SciML/OrdinaryDiffEq.jl#1386 should be closed once this PR is merged - you don't need to do this manually, i think

**Comment by jlchan** [comment]
Thanks! Much appreciated

**Pull request merged**
