### PR TITLE
fix any

### PR DESCRIPTION
**Pull request by bvdmitri**
This PR fixes https://github.com/SciML/RecursiveArrayTools.jl/issues/196

## Checklist

- [x] Appropriate tests were added
- [x] Any code changes were done in a way that does not break public API
- [x] All documentation related to code changes were updated
- [x] The new code follows the
  [contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
  [COLPRAC](https://github.com/SciML/COLPRAC).
- [x] Any new documentation only uses public API

### CODE REVIEW

**Review by ChrisRackauckas — APPROVED** [review]

**Comment by ChrisRackauckas** [comment]
```
 SymbolicIndexingInterface [2efcf032] log:
 ├─possible versions are: 0.1.0-0.3.22 or uninstalled
 └─restricted to versions 0.3.23 by RecursiveArrayTools [731186ca] — no versions left
   └─RecursiveArrayTools [731186ca] log:
     ├─possible versions are: 3.24.0 or uninstalled
     └─RecursiveArrayTools [731186ca] is fixed to version 3.24.0
```

@AayushSabharwal is this due to the recent yanks? We need to clean master here.

**Comment by AayushSabharwal** [comment]
Yes

**Comment by AayushSabharwal** [comment]
I'll revert the SII changes and PR

**Comment by bvdmitri** [comment]
Yeah, I needed to dev the SymbolicIndexingInterface in order to run tests locally (it passed)

**Comment by ChrisRackauckas** [comment]
Rebase onto the fixed master and you should be good.

**Pull request merged**
