### PR TITLE
fix: fix broadcasted assignment to VOA of StaticArrays

### PR DESCRIPTION
**Pull request by AayushSabharwal**
## Checklist

- [X] Appropriate tests were added
- [X] Any code changes were done in a way that does not break public API
- [X] All documentation related to code changes were updated
- [X] The new code follows the
  [contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
  [COLPRAC](https://github.com/SciML/COLPRAC).
- [X] Any new documentation only uses public API

### CODE REVIEW

**Comment by AayushSabharwal** [comment]
Why does CI randomly get cancelled like that?

**Comment by ChrisRackauckas** [comment]
fail fast

**Comment by AayushSabharwal** [comment]
Ah, so 1.6 is making it fail? I'll remove 1.6 CI so this actually runs

**Comment by ChrisRackauckas** [comment]
yes exactly. Just rebase onto master, it's being prepared to release all together

**Comment by AayushSabharwal** [comment]
This might need another rebase once https://github.com/SciML/RecursiveArrayTools.jl/pull/298 is merged

**Comment by ChrisRackauckas** [comment]
Rebase and 🙏

**Comment by ChrisRackauckas** [comment]
Looks like you have an infinite loop somewhere?

**Pull request merged**
