### PR TITLE
Test ChainRulesCore 1

### PR DESCRIPTION
**Pull request by ChrisRackauckas**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Anyone know what's going on with the chainrulescore update and why it would cause this? @oxinabox @DhairyaLGandhi 

https://github.com/SciML/RecursiveArrayTools.jl/pull/166/checks?check_run_id=3161312554#step:6:238

**Comment by DhairyaLGandhi** [comment]
First I'm seeing of this

**Comment by ChrisRackauckas** [comment]
It's only with ChainRulesCore 1.

**Comment by oxinabox** [comment]
You are using Zygote v0.4.20
https://github.com/SciML/RecursiveArrayTools.jl/pull/166/checks?check_run_id=3161312554#step:6:103

Which is truely ancient, given the current release is 0.6.17.
I recommend waiting before updating til we have https://github.com/FluxML/Zygote.jl/pull/1035 in
so that a modern version of Zygote works with ChainRules v1.
(I am looking into the remaining errors in the Zygote PR today and tomorrow)

**Pull request merged**
