### PR TITLE
remove functions that are predefined with `abstractarray` interface

### PR DESCRIPTION
**Pull request by vpuri3**
unless there's performance diff

### CODE REVIEW

**Comment by vpuri3** [comment]
All `Core` tests passed on my machine

**Comment by ChrisRackauckas** [comment]
What's the performance difference?

**Comment by vpuri3** [comment]
there isn't any. i meant to say "remove those functions unless there is a performance difference for for a particular use case". I don't see any.

**Comment by ChrisRackauckas** [comment]
Could you post some benchmarks?

**Comment by mateuszbaran** [comment]
Here are some benchmark examples I care about in case someone wants to check performance impact: https://github.com/SciML/RecursiveArrayTools.jl/issues/160

**Comment by vpuri3** [comment]
thanks will get to it

**Pull request closed without merging**
